### YamlMime:UniversalReference
ms.openlocfilehash: 777051058935475aebf2055932882ec0cd21fea9
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/13/2018
ms.locfileid: "52135176"
items:
- uid: azure-servicefabric.TestErrorChaosEvent
  name: TestErrorChaosEvent
  fullName: TestErrorChaosEvent
  children:
  - azure-servicefabric.TestErrorChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: >-
    <span data-ttu-id="7b4c4-101">Descrive un evento di Chaos viene generato quando si verifica un evento imprevisto nel motore di Chaos.</span><span class="sxs-lookup"><span data-stu-id="7b4c4-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>

    <span data-ttu-id="7b4c4-102">Ad esempio, a causa dello snapshot di cluster in corso incoerente, durante un'entità di generare un errore, Chaos individuato che l'entità è stata già verificati errori, che potrebbe essere un evento imprevisto.</span><span class="sxs-lookup"><span data-stu-id="7b4c4-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.TestErrorChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: <span data-ttu-id="7b4c4-103">Descrive il motivo per cui è stato generato TestErrorChaosEvent.</span><span class="sxs-lookup"><span data-stu-id="7b4c4-103">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="7b4c4-104">Ad esempio, Chaos tenta di una partizione di errore, ma individua che la partizione non è più a tolleranza di errore, quindi un TestErrorEvent generato con il motivo che informa che la partizione non è a tolleranza di errore.</span><span class="sxs-lookup"><span data-stu-id="7b4c4-104">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
